<a href="https://colab.research.google.com/github/sadidkhan/pytorch_essentials/blob/main/pytorch_01_03.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import torch

print(torch.__version__)
print(torch.cuda.is_available())

device = torch.device("cuda:0" if torch.cuda.is_available() else "cpu")
print(device)



2.8.0+cu126
True
cuda:0


In [12]:
tensor1 = torch.tensor([[12,10,11,9],[13,15,14,16]])
tensor2 = torch.tensor([[1,2,3,4],[5,6,7,8]])
print(tensor1)
print(tensor2)

add_tensor = tensor1 + tensor2
print(add_tensor)
print(add_tensor.size())

tensor([[12, 10, 11,  9],
        [13, 15, 14, 16]])
tensor([[1, 2, 3, 4],
        [5, 6, 7, 8]])
tensor([[13, 12, 14, 13],
        [18, 21, 21, 24]])
torch.Size([2, 4])


In [8]:
sub_tesnor = tensor1 - tensor2
print(sub_tesnor)

tensor([[11,  8,  8,  5],
        [ 8,  9,  7,  8]], device='cuda:0')


In [10]:
device = torch.device("cuda:0" if torch.cuda.is_available() else "cpu")
print(device)


tensor_A = torch.tensor([[1,2,3],[4,5,6]], device=device)
tensor_B = torch.tensor([[10,20,30],[40,50,60]], device=device)
print(tensor_A)
print(tensor_B)

mul_tensor = tensor_A * tensor_B
print(mul_tensor)

cuda:0
tensor([[1, 2, 3],
        [4, 5, 6]], device='cuda:0')
tensor([[10, 20, 30],
        [40, 50, 60]], device='cuda:0')
tensor([[ 10,  40,  90],
        [160, 250, 360]], device='cuda:0')


In [13]:
import numpy as np

tensor_from_list = torch.tensor([1,2,3,4,5])
print(tensor_from_list)


tensor_from_touple = torch.tensor((1,2,3,4,5))
print(tensor_from_touple)

tensor_from_numpy = torch.tensor(np.array([1,2,3,4,5]))
print(tensor_from_numpy)

tensor([1, 2, 3, 4, 5])
tensor([1, 2, 3, 4, 5])
tensor([1, 2, 3, 4, 5])
