<a href="https://colab.research.google.com/github/sadidkhan/pytorch_essentials/blob/main/pytorch_01_03.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import torch

print(torch.__version__)
print(torch.cuda.is_available())

device = torch.device("cuda:0" if torch.cuda.is_available() else "cpu")
print(device)



2.8.0+cu126
True
cuda:0


In [12]:
tensor1 = torch.tensor([[12,10,11,9],[13,15,14,16]])
tensor2 = torch.tensor([[1,2,3,4],[5,6,7,8]])
print(tensor1)
print(tensor2)

add_tensor = tensor1 + tensor2
print(add_tensor)
print(add_tensor.size())

tensor([[12, 10, 11,  9],
        [13, 15, 14, 16]])
tensor([[1, 2, 3, 4],
        [5, 6, 7, 8]])
tensor([[13, 12, 14, 13],
        [18, 21, 21, 24]])
torch.Size([2, 4])


In [8]:
sub_tesnor = tensor1 - tensor2
print(sub_tesnor)

tensor([[11,  8,  8,  5],
        [ 8,  9,  7,  8]], device='cuda:0')


In [10]:
device = torch.device("cuda:0" if torch.cuda.is_available() else "cpu")
print(device)


tensor_A = torch.tensor([[1,2,3],[4,5,6]], device=device)
tensor_B = torch.tensor([[10,20,30],[40,50,60]], device=device)
print(tensor_A)
print(tensor_B)

mul_tensor = tensor_A * tensor_B
print(mul_tensor)

cuda:0
tensor([[1, 2, 3],
        [4, 5, 6]], device='cuda:0')
tensor([[10, 20, 30],
        [40, 50, 60]], device='cuda:0')
tensor([[ 10,  40,  90],
        [160, 250, 360]], device='cuda:0')


In [15]:
import numpy as np

tensor_from_list = torch.tensor([1,2,3,4,5])
print("from list", tensor_from_list)


tensor_from_touple = torch.tensor((1,2,3,4,5))
print("from touple", tensor_from_touple)

tensor_from_numpy = torch.tensor(np.array([1,2,3,4,5]))
print("from numpy array",tensor_from_numpy)

from list tensor([1, 2, 3, 4, 5])
from touple tensor([1, 2, 3, 4, 5])
from numpy array tensor([1, 2, 3, 4, 5])


# Different functions to create tensors

In [16]:
empty_torch = torch.empty(2,3)
print("empty", empty_torch)

zero_tensor = torch.zeros(2,3)
print("sero", zero_tensor)

one_tensor = torch.ones(2,3)
print("one", one_tensor)


empty tensor([[3.6022e-12, 7.1223e+28, 3.0958e-18],
        [4.8354e+30, 1.1516e-38, 1.7419e+28]])
sero tensor([[0., 0., 0.],
        [0., 0., 0.]])
one tensor([[1., 1., 1.],
        [1., 1., 1.]])
rand tensor([[0.7345, 0.2935, 0.1863],
        [0.2979, 0.4035, 0.2621]])


In [17]:
random_tensor = torch.rand(2,3)
print("rand", random_tensor)

# random numbers between 0 and 1 (e.g., initialization, sampling probabilities).
random_tensor_uniform = torch.rand(4,5)
print("uniform", random_tensor_uniform)

random_tensor_normal = torch.randn(4,5)
print("normal", random_tensor_normal)

random_tensor_int = torch.randint(0,10,(4,5))
print("int", random_tensor_int)

rand tensor([[0.4312, 0.6736, 0.2079],
        [0.0132, 0.7635, 0.2186]])
uniform tensor([[0.5573, 0.5176, 0.6631, 0.6794, 0.9106],
        [0.7785, 0.5090, 0.4272, 0.9792, 0.5389],
        [0.5356, 0.3013, 0.8022, 0.3377, 0.5571],
        [0.3168, 0.4504, 0.5921, 0.6431, 0.8521]])
normal tensor([[-1.0427,  1.8181, -1.5166,  0.4169, -0.7777],
        [-1.6937, -1.4832, -0.3190,  0.9930,  1.3114],
        [ 0.4345,  1.1208,  0.7127, -1.5012, -0.9539],
        [-0.5668, -0.0423,  1.1608, -0.6446,  1.0335]])
int tensor([[4, 3, 6, 9, 4],
        [0, 1, 4, 5, 0],
        [0, 9, 3, 8, 0],
        [1, 6, 5, 9, 7]])


In [21]:
ones_tensor_like = torch.ones_like(random_tensor_int) # it will copy the shape, datatype and device type of random_tensor_int
print(ones_tensor_like)

#change it to randn
ones_tensor_like = torch.ones_like(random_tensor_)
print(ones_tensor_like)


tensor([[1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1]])
tensor([[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]])


# Tensor Attributes

In [24]:
import torch

tensor1 = torch.tensor([[12,10,11,9],[13,15,14,16]])


# device of tensor
print(tensor1.device)

#dtype of tensor
print(tensor1.dtype)

#shape of tensor
print(tensor1.shape)

#tensor dimension
print(tensor1.ndim)

cpu
torch.int64
torch.Size([2, 4])
2


# Tensor Data types

In [27]:
tensor1 = torch.tensor([[12,10,11,9],[13,15,14,16]], dtype=torch.float16)
print(tensor1)
print(tensor1.dtype)


tensor1 = tensor1.to(dtype=torch.int8)
print(tensor1)
print(tensor1.dtype)

tensor([[12., 10., 11.,  9.],
        [13., 15., 14., 16.]], dtype=torch.float16)
torch.float16
tensor([[12, 10, 11,  9],
        [13, 15, 14, 16]], dtype=torch.int8)
torch.int8


# Combine and spit tensor

In [46]:
tensor_two_dim = torch.randint(1,20, (4,6)).to(device=device)
print(tensor_two_dim)

# get tensors that has value less than 11

tensor_less_than_11 = tensor_two_dim[tensor_two_dim < 11]
print(tensor_less_than_11)

# to get the values in python way instead of torch, use numpy function, but before shift it from GPU to CPU
tensor_less_than_11 = tensor_less_than_11.cpu().numpy()
print(tensor_less_than_11)

#combine tensor
combine_tensor = torch.stack([tensor_two_dim, tensor_two_dim])
print(combine_tensor)


#split tensor
unbind_tesnor = torch.unbind(tensor_two_dim)
print(unbind_tesnor)

#split tensor by column
unbind_tesnor = torch.unbind(tensor_two_dim, dim = 1)
print(unbind_tesnor)






tensor([[15, 10,  1,  1, 12,  4],
        [ 7, 18,  4, 14, 18, 13],
        [14, 16, 11,  6, 12,  4],
        [14, 17,  2, 19, 19, 14]], device='cuda:0')
tensor([10,  1,  1,  4,  7,  4,  6,  4,  2], device='cuda:0')
[10  1  1  4  7  4  6  4  2]
tensor([[[15, 10,  1,  1, 12,  4],
         [ 7, 18,  4, 14, 18, 13],
         [14, 16, 11,  6, 12,  4],
         [14, 17,  2, 19, 19, 14]],

        [[15, 10,  1,  1, 12,  4],
         [ 7, 18,  4, 14, 18, 13],
         [14, 16, 11,  6, 12,  4],
         [14, 17,  2, 19, 19, 14]]], device='cuda:0')
(tensor([15, 10,  1,  1, 12,  4], device='cuda:0'), tensor([ 7, 18,  4, 14, 18, 13], device='cuda:0'), tensor([14, 16, 11,  6, 12,  4], device='cuda:0'), tensor([14, 17,  2, 19, 19, 14], device='cuda:0'))
(tensor([15,  7, 14, 14], device='cuda:0'), tensor([10, 18, 16, 17], device='cuda:0'), tensor([ 1,  4, 11,  2], device='cuda:0'), tensor([ 1, 14,  6, 19], device='cuda:0'), tensor([12, 18, 12, 19], device='cuda:0'), tensor([ 4, 13,  4, 14], device='